[workspace]
# Order is important as this is the order the crates will be released.
members = [
  "juniper_benchmarks",
  "juniper_codegen",
  "juniper",
  "examples/basic_subscriptions",
  "examples/warp_async",
  "examples/warp_subscriptions",
  "examples/actix_subscriptions",
  "juniper_hyper",
  "juniper_iron",
  "juniper_rocket",
  "juniper_subscriptions",
  "juniper_graphql_ws",
  "juniper_warp",
  "juniper_actix",
  "tests/codegen",
  "tests/integration",
]
exclude = [
  "docs/book/tests",
]
