[package]
name = "juniper"
version = "0.16.0-dev"
edition = "2018"
authors = [
    "Magnus Hallin <mhallin@fastmail.com>",
    "Christoph Herzog <chris@theduke.at>",
    "Christian Legnitto <christian@legnitto.com>",
]
description = "GraphQL server library"
license = "BSD-2-Clause"
documentation = "https://docs.rs/juniper"
repository = "https://github.com/graphql-rust/juniper"
readme = "../README.md"
keywords = ["graphql", "server", "web", "rocket"]
categories = ["web-programming"]

[badges]
travis-ci = { repository = "graphql-rust/juniper" }

[features]
default = [
    "bson",
    "schema-language",
    "url",
    "uuid",
]
chrono-clock = ["chrono", "chrono/clock"]
expose-test-schema = ["anyhow", "serde_json"]
schema-language = ["graphql-parser"]

[dependencies]
anyhow = { version = "1.0.32", default-features = false, optional = true }
async-trait = "0.1.39"
bson = { version = "2.0", features = ["chrono-0_4"], optional = true }
chrono = { version = "0.4", default-features = false, optional = true }
chrono-tz = { version = "0.6", default-features = false, optional = true }
fnv = "1.0.3"
futures = { version = "0.3.1", features = ["alloc"], default-features = false }
futures-enum = { version = "0.1.12", default-features = false }
graphql-parser = { version = "0.4", optional = true }
indexmap = { version = "1.0", features = ["serde-1"] }
juniper_codegen = { version = "0.16.0-dev", path = "../juniper_codegen" }
serde = { version = "1.0.8", features = ["derive"], default-features = false }
serde_json = { version = "1.0.2", default-features = false, optional = true }
smartstring = "1.0"
static_assertions = "1.1"
time = { version = "0.3", features = ["formatting", "macros", "parsing"], optional = true }
url = { version = "2.0", optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
uuid = { version = "0.8", default-features = false, optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }
uuid = { version = "0.8", default-features = false, features = ["wasm-bindgen"], optional = true }

[dev-dependencies]
bencher = "0.1.2"
pretty_assertions = "1.0.0"
serde_json = "1.0.2"
tokio = { version = "1", features = ["macros", "time", "rt-multi-thread"] }

[[bench]]
name = "bench"
harness = false
path = "benches/bench.rs"
