[package]
name = "juniper_hyper"
version = "0.8.0"
edition = "2018"
authors = ["Damir Vandic <info@dvic.io>"]
description = "Juniper GraphQL integration with Hyper"
license = "BSD-2-Clause"
documentation = "https://docs.rs/juniper_hyper"
repository = "https://github.com/graphql-rust/juniper"

[dependencies]
futures = "0.3.1"
hyper = { version = "0.14", features = ["server", "runtime"] }
juniper = { version = "0.16.0-dev", path = "../juniper", default-features = false }
serde_json = "1.0"
tokio = "1.0"
url = "2.0"

[dev-dependencies]
juniper = { version = "0.16.0-dev", path = "../juniper", features = ["expose-test-schema"] }
pretty_env_logger = "0.4"
reqwest = { version = "0.11", features = ["blocking", "rustls-tls"] }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
